logging:
  level: "info"          # debug, info, warn, error
  file: "logs/s3mgr.log"
  max_size: 100          # MB
  max_backups: 30        # Number of backup files to keep
  max_age: 30            # Days to keep log files
  compress: true         # Compress old log files
  console: true          # Also log to console
  format: "json"         # json or text

server:
  port: 8081
  host: "0.0.0.0"
  read_timeout: 30       # seconds
  write_timeout: 30      # seconds
  
database:
  path: "s3mgr.db"

jwt:
  secret: "your-secret-key-here"
  expiry_hours: 24

minio_admin:
  url: "http://localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"

minio_default:
  endpoint: "localhost:9000"
  bucket: "s3mgr-default"
  region: "us-east-1"
  ssl: false
